image: maven:3.6.1-jdk-11

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GPG_CLI_OPTS: "--pinentry-mode loopback"

#before_script:
# - gpg $GPG_CLI_OPTS --passphrase $GPG_PASSPHRASE --import $GPG_USER_KEY

cache:
 paths:
   - .m2/repository/
   - target/

build:
 stage: build
 script:
   - mvn $MAVEN_CLI_OPTS compile

test:
 stage: test
 script:
   - mvn $MAVEN_CLI_OPTS test
   
# deploy:
#   stage: deploy
#   script:
#     - mvn $MAVEN_CLI_OPTS deploy -P release $MAVEN_OPTS
